#!/bin/bash

# Disk monitoring script

THRESHOLD=80

USAGE=$(df / | tail -1 | awk '{print $(NF-1)}' | sed 's/%//')

echo "current Disk Usage: $USAGE%"

if [ $USAGE -gt $THRESHOLD ]
then 
   echo "WARNING: Disk usage is above $THRESHOLD%"
else 
   echo "Disk usage is normal"
fi
